#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/dev -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
#     tmux new-session -s $selected_name -c $selected
#     exit 0
# fi
#
# if ! tmux has-session -t=$selected_name 2> /dev/null; then
#     tmux new-session -ds $selected_name -c $selected
# fi
#
# tmux switch-client -t $selected_name


if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "Not in tmux session, tmux not running"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if [[ -z $TMUX ]] && [[ ! -z $tmux_running ]]; then
    echo
    if tmux has-session -t=$selected_name 2> /dev/null; then
        echo "Not in tmux session, tmux is running, tmux has session"
        tmux attach -t=$selected_name
    else
        echo "Not in tmux session, tmux is running, tmux does not have session"
        echo $selected_name
        echo $selected
        tmux new-session -s $selected_name -c $selected
    fi

    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

echo "switching to session"k
tmux switch-client -t $selected_name
